"""Configuration utilities for the machine-level training pipeline."""

from __future__ import annotations

from pathlib import Path
from typing import List, Dict, Any

# Import shared config from planogram package
try:
    from planogram import config as shared_config
except ImportError:
    # Fallback for when running as a script without package context
    import sys
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from planogram import config as shared_config

PACKAGE_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = PACKAGE_ROOT / "output"
MODEL_OUTPUT_DIR = OUTPUT_DIR / "models"
METRICS_OUTPUT_DIR = OUTPUT_DIR / "metrics"
SNAPSHOT_DIR = OUTPUT_DIR / "snapshots"
FEATURE_DIR = OUTPUT_DIR / "features"

for d in [OUTPUT_DIR, MODEL_OUTPUT_DIR, METRICS_OUTPUT_DIR, SNAPSHOT_DIR, FEATURE_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# Use paths from shared config
RAW_DATA_DIR = Path(shared_config.PROCESSED_SALES_DATA_PATH)

# Machine snapshots path (assumed to be in sibling directory or configurable)
# If machine_snapshots is not available, we might need to rely on raw data only
MACHINE_SNAPSHOT_DIR = PACKAGE_ROOT.parent / "machine_snapshots" / "data"
PREBUILT_SNAPSHOT_PATH = MACHINE_SNAPSHOT_DIR / "machine_snapshots.parquet"

# Planogram-trained artifact locations (default)
UNIQUE_SCORE_DIR = PACKAGE_ROOT.parent / "parquet_unique_product_score" / "output"
UNIQUE_SLOT_SCORES = UNIQUE_SCORE_DIR / "machine_slot_scores.parquet"
LOCATION_MODEL_ARTIFACT_PATH = MODEL_OUTPUT_DIR / "location_model.pkl"
UNIQUENESS_MODEL_ARTIFACT_PATH = MODEL_OUTPUT_DIR / "uniqueness_model.pkl"

# Uniqueness scores path (default location for machine slot scores)
# This assumes uniqueness scores are generated by a separate pipeline
UNIQUE_SCORE_DIR = PACKAGE_ROOT.parent / "parquet_unique_product_score" / "output"
UNIQUE_SLOT_SCORES = UNIQUE_SCORE_DIR / "machine_slot_scores.parquet"

# Sales files typically follow Sales_YYYY.parquet naming
SALES_FILE_TEMPLATE = "Sales_{year}.parquet"
DATA_YEARS: List[int] = list(range(2018, 2026))

# Snapshot defaults
SNAPSHOT_FREQ = "W-SUN"  # ISO weeks ending on Sunday
LOOKBACK_WEEKS = 4
MIN_SALES_PER_POSITION = 0

DEFAULT_SNAPSHOT_OUTPUT = SNAPSHOT_DIR / "machine_weekly_snapshots.parquet"
DEFAULT_FEATURE_DATASET = FEATURE_DIR / "machine_weekly_features.parquet"

# Column aliases to align with uniqueness + snapshot pipelines
COLUMN_ALIASES = {
    "machine_key": "machine_id",
    "machine": "machine_id",
    "local_timestamp": "event_ts",
}

REQUIRED_COLUMNS = {
    "machine_id",
    "position",
    "event_ts",
    "ean",
}

TARGET_COLUMN = "weekly_sales"
IDENTITY_COLUMNS = ["machine_id", "snapshot_date", "position", "ean"]

XGBOOST_PARAMS: Dict[str, Any] = {
    "n_estimators": 300,
    "max_depth": 9,
    "learning_rate": 0.0369,
    "subsample": 0.92,
    "colsample_bytree": 0.99,
    "reg_alpha": 10,
    "reg_lambda": 0,
    "min_child_weight": 20,
    "random_state": 42,
    "tree_method": "hist",
    "n_jobs": -1,
}

# Global training split params
DEFAULT_TEST_SIZE = 0.2
MIN_TRAIN_ROWS = 1000 # Increased for global model to ensure stability
